repos:
  - repo: local
    hooks:
      # Copies the default .terraform-docs.yml to all the modules folders to keep consistency in documentation
      - id: copy-terraform-docs-config
        name: Copy terraform-docs config to module folders
        entry: >
          pwsh -NoProfile -Command "
          Get-ChildItem -Recurse -Include *.tf |
            Select-Object -ExpandProperty Directory |
            Sort-Object -Unique |
            Where-Object {
              $_ -notmatch '^\.$' -and
              $_ -notmatch '/test/'
            } |
            ForEach-Object {
              Copy-Item -Path ./.terraform-docs.yaml -Destination (Join-Path $_ '.terraform-docs.yaml') -Force
            }
          "
        language: system
        pass_filenames: false

      - id: terraform-docs
        name: Generate Terraform docs
        entry: >
          pwsh -NoProfile -Command "
          Get-ChildItem -Recurse -Include *.tf |
            Select-Object -ExpandProperty Directory |
            Sort-Object -Unique |
            Where-Object {
              $_ -notmatch '/test/'
            } |
            ForEach-Object {
              & terraform-docs $_
            }
          "
        language: system
        pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.98.1"
    hooks:
      - id: terraform_fmt
        args: [--args=-write=true]
      - id: terraform_tflint
        args:
          - --hook-config=--delegate-chdir
      - id: terraform_trivy
        args: 
          - config . --severity CRITICAL
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true