name: PR Tests

on:
  pull_request:
    branches:
      - testing_branch
    paths:
      - '**/*.tf'
    
jobs:
  detect_changes:
    runs-on: ubuntu-latest

    outputs:
      aap_asm: ${{ steps.filter.outputs.aap_asm }}
      aap: ${{ steps.filter.outputs.aap }}
      bmp: ${{ steps.filter.outputs.bmp }}
      delivery: ${{ steps.filter.outputs.delivery }}
      dv_san_cert: ${{ steps.filter.outputs.dv_san_cert }}
      edns: ${{ steps.filter.outputs.edns }}
      third_party_cert: ${{ steps.filter.outputs.third_party_cert }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed folders
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            aap_asm:
              - 'aap-asm/**'
            aap:
              - 'aap/**'
            bmp:
              - 'bmp/**'
            delivery:
              - 'delivery/**'
            dv_san_cert:
              - 'dv-san-cert/**'
            edns:
              - 'edns/**'
            third_party_cert:
              - 'third-party-cert/**'

  aap_asm:
    needs: detect_changes
    if: needs.detect_changes.outputs.aap_asm == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: aap_asm
    secrets: inherit


    
  aap:
    needs: detect_changes
    if: needs.detect_changes.outputs.aap == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: aap
    secrets: inherit

  bmp:
    needs: detect_changes
    if: needs.detect_changes.outputs.bmp == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: bmp
    secrets: inherit

  delivery:
    needs: detect_changes
    if: needs.detect_changes.outputs.delivery == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: delivery
    secrets: inherit

  dv_san_cert:
    needs: detect_changes
    if: needs.detect_changes.outputs.dv_san_cert == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: dv_san_cert
    secrets: inherit

  edns:
    needs: detect_changes
    if: needs.detect_changes.outputs.edns == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: edns
    secrets: inherit

  third_party_cert:
    needs: detect_changes
    if: needs.detect_changes.outputs.third_party_cert == 'true'
    uses: ./.github/workflows/pr-tests.yml
    with:
        test_type: third_party_cert
    secrets: inherit