name: Delivery Tests

on:
  workflow_call:


jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          CONFIG_FILE="test_config_files/delivery.json"
          MAX=2

          MATRIX=$(jq -cn \
            --argjson cfg "$(cat "$CONFIG_FILE")" \
            --argjson max "$MAX" '
            
            def build(idx; current; keys):
              if idx == (keys | length) then
                current
              else
                keys[idx] as $k
                | $cfg[$k][] as $val
                | build(idx + 1; current + { ($k): $val }; keys)
              end;

            [
              limit($max; build(0; {}; $cfg | keys_unsorted))
              | . + {
                  label: (
                    to_entries
                    | map("\(.key)=\(.value)")
                    | join(", ")
                  )
                }
            ]
          ')

          MATRIX=$(echo "$MATRIX" | jq -c '.[]' | while read -r item; do
          r="a$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 10)"
          echo "$item" | jq -c --arg r "$r" '
            . + { 
              name: $r, 
              label: (.label + ", name=\($r)") 
            }'
          done | jq -cs '.')

          echo "Generated matrix:"
          echo "$MATRIX"

          echo "matrix={\"include\":$MATRIX}" >> "$GITHUB_OUTPUT"

      - name: Print all permutations
        run: |
          echo "===== ALL GENERATED PERMUTATIONS ====="
          echo '${{ steps.set-matrix.outputs.matrix }}' | jq '.'
            
  delivery-tests:
    name: (${{ matrix.label }})
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    env:
      AKAMAI_HOST: ${{ secrets.HOST }}
      AKAMAI_CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
      AKAMAI_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      AKAMAI_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AKAMAI_ACCOUNT_KEY: "1-5BYUG1:1-8BYUX"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Prepare Terraform
        run: |
          cd delivery

          cat << EOF > terraform.tfvars
          edgerc_section = "default"
          contract_id = "ctr_1-5C13O2"
          group_id = "grp_315874"
          hostnames = ["${{ matrix.name }}.terra.rafa.cr"]
          name = "${{ matrix.name }}.terra.rafa.cr"
          cpcode_name = "${{ matrix.name }}.terra.rafa.cr"
          default_origin = "flexibleorigin.rafa.cr"
          notification_emails = ["test@akamai.com"]
          version_notes = "GitHub Actions test"
          certificate_id = 30192
          peer_reviewed_by = "test@na.com"
          customer_email = "test@akamai.com"
          unit_tested = true
          ticket_id = "some-ticket-id"
          noncompliance_reason = ["NONE"]
          other_noncompliance_reason = "test"
          td_region = "CH2"
          ip_behavior = "IPV6_PERFORMANCE"
          sure_route_test_object = "/terraform/srto.html"
          activation_notes = "GitHub Actions test"
          activation_to_staging_exists = false
          activation_to_production_exists = false
          additional_origins=null
          EOF

          echo 'provider "akamai" {}' >> provider.tf
          terraform init

      - name: Apply test case variables
        run: |
          cd delivery

          echo "etls=${{ matrix.etls }}" >> terraform.tfvars
          echo "secure_by_default=${{ matrix.secure_by_default }}" >> terraform.tfvars
          echo "product_id=\"${{ matrix.product_id }}\"" >> terraform.tfvars
          echo "activate_to_staging=${{ matrix.activate_to_staging }}" >> terraform.tfvars
          echo "activate_to_production=${{ matrix.activate_to_production }}" >> terraform.tfvars

      - name: Terraform fmt & validate
        run: |
          cd delivery
          terraform fmt
          terraform validate

      - name: Terraform plan
        run: |
          pwd
          cd delivery
          set -x
          terraform plan -out=tfplan -detailed-exitcode 

          #set -e
          #set -x
          #terraform plan -out=tfplan -detailed-exitcode 
          # > tfplan.txt
          # EXIT=$?
          # set -e

          # if [ "$EXIT" = "1" ]; then
          #   cat tfplan.txt
          #   exit 1
          # fi

      - name: Terraform apply
        run: |
          cd delivery
          terraform apply -auto-approve tfplan

      - name: Wait
        run: sleep 60

      - name: Terraform destroy
        run: |
          cd delivery
          terraform destroy -auto-approve