name: Delivery Tests

on:
  workflow_call:
    inputs:
      module_source:
        required: true
        type: string
      module_mode:
        required: false
        type: string
        default: "none" 
jobs:
  
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate test permutations matrix
        id: set-matrix
        run: |
          CONFIG_FILE="${{ inputs.module_source }}/tests/config.json"
          MAX=50

          MATRIX=$(jq -cn \
            --argjson cfg "$(cat "$CONFIG_FILE")" \
            --argjson max "$MAX" '
            
            def build(idx; current; keys):
              if idx == (keys | length) then
                current
              else
                keys[idx] as $k
                | $cfg[$k][] as $val
                | build(idx + 1; current + { ($k): $val }; keys)
              end;

            [
              limit($max; build(0; {}; $cfg | keys_unsorted))
              | . + {
                  label: (
                    to_entries
                    | map("\(.key)=\(.value)")
                    | join(", ")
                  )
                }
            ]
          ')

          MATRIX=$(echo "$MATRIX" | jq -c '.[]' | while read -r item; do
          r="a$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 10)"
          echo "$item" | jq -c --arg r "$r" '
            . + { 
              name: $r, 
              label: (.label + ", name=\($r)") 
            }'
          done | jq -cs '.')

          echo "Generated matrix:"
          echo "$MATRIX"

          echo "matrix={\"include\":$MATRIX}" >> "$GITHUB_OUTPUT"

      - name: Print all permutations
        run: |
          echo "===== ALL GENERATED PERMUTATIONS ====="
          echo '${{ steps.set-matrix.outputs.matrix }}' | jq '.'
            
  delivery-tests:
    name: ${{ matrix.label }}
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    env:
      AKAMAI_HOST: ${{ secrets.HOST }}
      AKAMAI_CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
      AKAMAI_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      AKAMAI_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AKAMAI_ACCOUNT_KEY: "1-5BYUG1:1-8BYUX"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Prepare Terraform tfvars
        run: |
          TFVARS_TEMPLATE="${{ inputs.module_source }}/tests/tfvars.tpl"

          # Dynamically export all matrix variables as uppercase env vars
          while IFS= read -r line; do
            export "$line"
          done < <(echo '${{ toJson(matrix) }}' | jq -r '
            to_entries[] |
            if .key == "name" then "MATRIX_NAME=\(.value)"
            elif .key == "label" then empty
            else "\(.key | ascii_upcase)=\(.value)"
            end
          ')

          cd "${{ inputs.module_source }}"
          
          envsubst < "../$TFVARS_TEMPLATE" > "terraform.tfvars"
          echo "" >> "terraform.tfvars"
          
      - name: Prepare Terraform tf files
        run: |
          cd "${{ inputs.module_source }}"
          
          if [ "${{ inputs.module_mode }}" == "full" ]; then
            cp "tests/main.tf.tpl" "main.tf"
            cp "tests/variables.tf.tpl" "variables.tf"
            cp "tests/outputs.tf.tpl" "outputs.tf"
            cp "tests/versions.tf.tpl" "versions.tf"
          fi

          echo 'provider "akamai" {}' >> "provider.tf"
    
      - name: Terraform init
        run: |
          cd "${{ inputs.module_source }}"
          terraform init

      - name: Terraform plan
        run: |
          cd "${{ inputs.module_source }}"

          # -u        → fail on undefined variables
          # pipefail  → detect failures in pipes
          # +e        → DO NOT exit on errors
          # -x        → print commands
          #           set -uo pipefail
          #           set -x
          
          set -uo pipefail
          set +e
          set -x

          terraform plan -input=false -detailed-exitcode -no-color -out=tfplan > >(tee /dev/tty) 2> >(tee plan.out >&2)
          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "::error title=Terraform Plan Failed::Check summary for details"
            
            echo "## ❌ Terraform Plan Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Module:**  ${{ inputs.module_source }} " >> $GITHUB_STEP_SUMMARY
            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY
 
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 plan.out >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Terraform apply
        run: |
          cd "${{ inputs.module_source }}"
          
          set -uo pipefail
          set +e
          set -x

          #terraform apply -input=false -auto-approve -no-color tfplan > >(tee /dev/tty) 2> >(tee apply.out >&2)
          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "::error title=Terraform Plan Failed::Check summary for details"
            
            echo "## ❌ Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Module:**  ${{ inputs.module_source }} " >> $GITHUB_STEP_SUMMARY
            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 apply.out >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Wait
        run: sleep 60

      - name: Terraform destroy
        run: |
          cd "${{ inputs.module_source }}"
          set -uo pipefail
          set +e
          set -x

          #terraform destroy -input=false -auto-approve -no-color > >(tee /dev/tty) 2> >(tee destroy.out >&2)          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "::error title=Terraform Destroy Failed::Check summary for details"
            
            echo "## ❌ Terraform Apply Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Module:**  ${{ inputs.module_source }} " >> $GITHUB_STEP_SUMMARY
            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 apply.out >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi
