name: Delivery Tests

on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string


jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          CONFIG_FILE="test_config_files/${{ inputs.test_type }}.json"
          MAX=50

          MATRIX=$(jq -cn \
            --argjson cfg "$(cat "$CONFIG_FILE")" \
            --argjson max "$MAX" '
            
            def build(idx; current; keys):
              if idx == (keys | length) then
                current
              else
                keys[idx] as $k
                | $cfg[$k][] as $val
                | build(idx + 1; current + { ($k): $val }; keys)
              end;

            [
              limit($max; build(0; {}; $cfg | keys_unsorted))
              | . + {
                  label: (
                    to_entries
                    | map("\(.key)=\(.value)")
                    | join(", ")
                  )
                }
            ]
          ')

          MATRIX=$(echo "$MATRIX" | jq -c '.[]' | while read -r item; do
          r="a$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 10)"
          echo "$item" | jq -c --arg r "$r" '
            . + { 
              name: $r, 
              label: (.label + ", name=\($r)") 
            }'
          done | jq -cs '.')

          echo "Generated matrix:"
          echo "$MATRIX"

          echo "matrix={\"include\":$MATRIX}" >> "$GITHUB_OUTPUT"

      - name: Print all permutations
        run: |
          echo "===== ALL GENERATED PERMUTATIONS ====="
          echo '${{ steps.set-matrix.outputs.matrix }}' | jq '.'
            
  delivery-tests:
    name: ${{ matrix.label }}
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    env:
      AKAMAI_HOST: ${{ secrets.HOST }}
      AKAMAI_CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
      AKAMAI_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      AKAMAI_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AKAMAI_ACCOUNT_KEY: "1-5BYUG1:1-8BYUX"


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Prepare Terraform files
        run: |
          pwd
          TEMPLATE="test_config_files/${{ inputs.test_type }}.tfvars.template"

          export MATRIX_NAME="${{ matrix.name }}"
          export ETLS="${{ matrix.etls }}"
          export SECURE_BY_DEFAULT="${{ matrix.secure_by_default }}"
          export PRODUCT_ID="${{ matrix.product_id }}"
          export ACTIVATE_TO_STAGING="${{ matrix.activate_to_staging }}"
          export ACTIVATE_TO_PRODUCTION="${{ matrix.activate_to_production }}"

          cd "${{ inputs.test_type }}"
          
          envsubst < "../$TEMPLATE" > "terraform.tfvars"
          echo "" >> "terraform.tfvars"
          echo 'provider "akamai" {}' >> "provider.tf"
          terraform init

      - name: Terraform plan
        run: |
          cd "${{ inputs.test_type }}"

          # -u        → fail on undefined variables
          # pipefail  → detect failures in pipes
          # +e        → DO NOT exit on errors
          # -x        → print commands
          #           set -uo pipefail
          #           set -x
          
          set -uo pipefail
          set +e
          set -x
          
          #terraform plan -out=tfplan -detailed-exitcode 
          #terraform plan -input=false -no-color -out=tfplan 2>&1 | tee plan.out
          
          #terraform plan -input=false -detailed-exitcode -out=tfplan 2>&1 | tee plan.out

          terraform plan -input=false -detailed-exitcode -out=tfplan > >(tee /dev/tty) 2> >(tee plan.out >&2)
          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "::error title=Terraform Plan Failed::Check summary for details"
            
            echo "## ❌ Terraform Plan Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Module:**  ${{ inputs.test_type }} " >> $GITHUB_STEP_SUMMARY
            echo "**Test:** ${{ matrix.label }}" >> $GITHUB_STEP_SUMMARY
            echo "**Exit Code:** $EXIT_CODE" >> $GITHUB_STEP_SUMMARY

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🧾 Error Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 plan.out >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Terraform apply
        run: |
          cd "${{ inputs.test_type }}"
          #terraform apply -auto-approve tfplan

      - name: Wait
        run: sleep 60

      - name: Terraform destroy
        run: |
          cd "${{ inputs.test_type }}"
          #terraform destroy -auto-approve