name: Terraform Docs

on:
  push:
    branches:
      - integration
    paths:
      - '**.tf'
      - '**.terraform-docs.yml'
      - '.github/workflows/**.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Terraform Docs Update
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate terraform-docs for AAP - Activate Security Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap/activate-security
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP - Bot Manager Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap/bot-manager
          output-file: README.md
          output-method: inject
          git-push: true
      
      - name: Generate terraform-docs for AAP - Client Lists Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap/client-lists
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP - Security Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap/security
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM - Activate Security Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap-asm/activate-security
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM - Bot Manager Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap-asm/bot-manager
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM - Client Lists Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap-asm/client-lists
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM - Client Reputation Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap-asm/client-reputation
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM - Security Module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./aap-asm/security
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for Delivery
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./delivery
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for CPS - DV SAN
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./dv-san-cert
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for CPS - Third Party
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./third-party-cert
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for BMP - API Definition
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./bmp/api-definition
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for BMP - Transactional Endpoint
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./bmp/transactional-endpoint
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for BMP - Security Configuration Activation
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./bmp/security-config-activation
          output-file: README.md
          output-method: inject
          git-push: true          